# [nfs]
# <NFS-Server-Private-IP-Address> ansible_ssh_user=ec2-user

# [webservers]
# 172.31.41.226 ansible_ssh_user=ec2-user
# #<Web-Server2-Private-IP-Address> ansible_ssh_user=ec2-user

# [db]
# 172.31.30.167 ansible_ssh_user=ubuntu 

 [lb]
# 172.31.41.88 ansible_ssh_user=ubuntu
  172.31.47.162 ansible_ssh_user=ubuntu
