---
# - hosts: db
# - name: database assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: nginx
# - name: nginx assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: artifactory
# - name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

- hosts: todo
- name: Deploy the todo application
  ansible.builtin.import_playbook: ../static-assignments/php.yml

# - hosts: sonarqube
# - name: sonarqube assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: sonar
# - name: sonarqube assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml